# Generated by Django 5.0.6 on 2024-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='type',
            field=models.CharField(choices=[('width', 'Ширина'), ('height', 'Висота'), ('weight', 'Вага'), ('color', 'Колір'), ('size', "Об'єм"), ('manufacturer', 'Виробник')], max_length=500),
        ),
    ]
