<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApi', '0002_alter_characteristic_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='name',
        ),
    ]
=======
# Generated by Django 5.0.6 on 2024-05-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApi', '0002_alter_characteristic_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='name',
        ),
    ]
>>>>>>> 7bb3b2e6bebba61021555f09a5c46875067a0008
