<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApi', '0006_alter_product_description_alter_product_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_number',
            field=models.IntegerField(null=True),
        ),
    ]
=======
# Generated by Django 5.0.6 on 2024-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApi', '0006_alter_product_description_alter_product_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_number',
            field=models.IntegerField(null=True),
        ),
    ]
>>>>>>> 7bb3b2e6bebba61021555f09a5c46875067a0008
