# Generated by Django 5.0.6 on 2024-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApi', '0007_alter_product_review_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='type',
            field=models.CharField(choices=[('width', 'Ширина'), ('height', 'Висота'), ('weight', 'Вага'), ('color', 'Колір'), ('size', "Об'єм"), ('Country manufacturer', 'Країна виробник')], max_length=500),
        ),
    ]
